name: Deploy Vaadin Portfolio to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-vaadin-app  # Update with your Azure app name
  JAVA_VERSION: '17'                  # Vaadin 24+ requires Java 17
  DISTRIBUTION: temurin               # Recommended JDK distribution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        cache: 'maven'

    - name: Build with Maven (Production Mode)
      run: |
        ./mvnw clean package -Pproduction

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: vaadin-app
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy.outputs.webapp-url }}

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: vaadin-app

    - name: Deploy to Azure Web App
      id: deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '*.jar'
